# -*- coding: utf-8 -*-
"""
Lista de ingredientes de las recetas.

Cada uno se ata a dos fuentes reales:
  usda: descripcion exacta en USDA FoodData Central (SR Legacy, dominio publico)
  off:  nodo de la taxonomia de ingredientes de Open Food Facts (origen y alergenos)

Nada se rellena a mano: la nutricion sale de USDA y el origen de OFF.
"""

# (id, nombre en espanol, texto para buscar en USDA, nodo de Open Food Facts)
INGREDIENTES = [
    # Legumbres
    ("lentejas", "Lentejas cocidas", "Lentils, mature seeds, cooked, boiled, without salt", "en:lentils"),
    ("garbanzos", "Garbanzos cocidos", "Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt", "en:chickpea"),
    ("alubias-blancas", "Alubias blancas cocidas", "Beans, white, mature seeds, cooked, boiled, without salt", "en:white-beans"),
    ("judias-pintas", "Judías pintas cocidas", "Beans, pinto, mature seeds, cooked, boiled, without salt", "en:pinto-beans"),
    ("guisantes", "Guisantes", "Peas, green, frozen, cooked, boiled, drained, without salt", "en:pea"),
    ("proteina-soja", "Proteína de soja", "Soy protein concentrate, produced by alcohol extraction", "en:soya"),
    # Cereales y pan
    ("arroz-blanco", "Arroz blanco cocido", "Rice, white, long-grain, regular, enriched, cooked", "en:white-rice"),
    ("arroz-integral", "Arroz integral cocido", "Rice, brown, long-grain, cooked (Includes foods for USDA's Food Distribution Program)", "en:whole-grain-rice"),
    ("pasta", "Pasta cocida", "Pasta, cooked, enriched, without added salt", "en:pasta"),
    ("pasta-integral", "Pasta integral cocida", "Pasta, whole-wheat, cooked (Includes foods for USDA's Food Distribution Program)", "en:dry-whole-wheat-pasta"),
    ("pan", "Pan blanco", "Bread, white, commercially prepared (includes soft bread crumbs)", "en:bread"),
    ("pan-integral", "Pan integral", "Bread, whole-wheat, commercially prepared", "en:bread"),
    ("avena", "Copos de avena", "Oats (Includes foods for USDA's Food Distribution Program)", "en:oat-flakes"),
    ("quinoa", "Quinoa cocida", "Quinoa, cooked", "en:quinoa"),
    ("cuscus", "Cuscús cocido", "Couscous, cooked", "en:couscous"),
    ("harina-trigo", "Harina de trigo", "Wheat flour, white, all-purpose, enriched, bleached", "en:wheat-flour"),
    ("maiz-dulce", "Maíz dulce", "Corn, sweet, yellow, canned, whole kernel, drained solids", "en:corn"),
    # Verduras
    ("cebolla", "Cebolla", "Onions, raw", "en:onion"),
    ("ajo", "Ajo", "Garlic, raw", "en:garlic"),
    ("tomate", "Tomate", "Tomatoes, red, ripe, raw, year round average", "en:tomato"),
    ("tomate-triturado", "Tomate triturado", "Tomatoes, crushed, canned", "en:crushed-peeled-tomato"),
    ("pimiento", "Pimiento", "Peppers, sweet, red, raw", "en:red-bell-pepper"),
    ("calabacin", "Calabacín", "Squash, summer, zucchini, includes skin, raw", "en:courgette"),
    ("berenjena", "Berenjena", "Eggplant, raw", "en:aubergine"),
    ("zanahoria", "Zanahoria", "Carrots, raw", "en:carrot"),
    ("patata", "Patata", "Potatoes, flesh and skin, raw", "en:potato"),
    ("boniato", "Boniato", "Sweet potato, raw, unprepared (Includes foods for USDA's Food Distribution Program)", "en:sweet-potato"),
    ("brocoli", "Brócoli", "Broccoli, raw", "en:broccoli"),
    ("coliflor", "Coliflor", "Cauliflower, raw", "en:cauliflower"),
    ("espinacas", "Espinacas", "Spinach, raw", "en:spinach"),
    ("acelgas", "Acelgas", "Chard, swiss, raw", "en:chard"),
    ("judias-verdes", "Judías verdes", "Beans, snap, green, raw", "en:green-bean"),
    ("champinones", "Champiñones", "Mushrooms, white, raw", "en:mushroom"),
    ("puerro", "Puerro", "Leeks, (bulb and lower leaf-portion), raw", "en:leek"),
    ("calabaza", "Calabaza", "Pumpkin, raw", "en:pumpkin"),
    ("lechuga", "Lechuga", "Lettuce, cos or romaine, raw", "en:lettuce"),
    ("pepino", "Pepino", "Cucumber, with peel, raw", "en:cucumber"),
    ("col", "Col", "Cabbage, raw", "en:cabbage"),
    ("apio", "Apio", "Celery, raw", "en:celery"),
    # Frutas
    ("manzana", "Manzana", "Apples, raw, gala, with skin (Includes foods for USDA's Food Distribution Program)", "en:apple"),
    ("platano", "Plátano", "Bananas, raw", "en:banana"),
    ("naranja", "Naranja", "Oranges, raw, all commercial varieties", "en:orange"),
    ("limon", "Limón", "Lemons, raw, without peel", "en:lemon"),
    ("fresas", "Fresas", "Strawberries, raw", "en:strawberry"),
    ("aguacate", "Aguacate", "Avocados, raw, all commercial varieties", "en:avocado"),
    ("pera", "Pera", "Pears, raw", "en:pear"),
    ("uvas", "Uvas", "Grapes, red or green (European type, such as Thompson seedless), raw", "en:grape"),
    ("datiles", "Dátiles", "Dates, medjool", "en:date"),
    ("pasas", "Pasas", "Raisins, dark, seedless (Includes foods for USDA's Food Distribution Program)", "en:raisin"),
    # Carne y pescado
    ("pollo", "Pechuga de pollo", "Chicken, broilers or fryers, breast, meat only, cooked, roasted", "en:chicken-breast"),
    ("pavo", "Pechuga de pavo", "Turkey, breast, from whole bird, meat only, with added solution, roasted", "en:turkey-breast"),
    ("ternera", "Ternera magra", "Beef, round, top round, separable lean only, trimmed to 0\" fat, choice, cooked, braised", "en:beef"),
    ("cerdo-lomo", "Lomo de cerdo", "Pork, fresh, loin, center loin (chops), bone-in, separable lean only, cooked, braised", "en:pork"),
    ("jamon", "Jamón en lonchas", "Ham, sliced, regular (approximately 11% fat)", "en:ham"),
    ("huevo", "Huevo", "Egg, whole, cooked, hard-boiled", "en:egg"),
    ("atun-lata", "Atún en lata al natural", "Fish, tuna, light, canned in water, without salt, drained solids", "en:canned-tuna"),
    ("salmon", "Salmón", "Fish, salmon, Atlantic, farmed, cooked, dry heat", "en:salmon"),
    ("bacalao", "Bacalao", "Fish, cod, Atlantic, cooked, dry heat", "en:cod"),
    ("sardinas", "Sardinas en lata", "Fish, sardine, Atlantic, canned in oil, drained solids with bone", "en:sardine"),
    ("gambas", "Gambas", "Crustaceans, shrimp, cooked", "en:shrimp"),
    ("mejillones", "Mejillones", "Mollusks, mussel, blue, cooked, moist heat", "en:mussel"),
    # Lacteos
    ("leche-entera", "Leche entera", "Milk, whole, 3.25% milkfat, with added vitamin D", "en:whole-milk"),
    ("leche-desnatada", "Leche desnatada", "Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)", "en:skimmed-milk"),
    ("yogur-natural", "Yogur natural", "Yogurt, plain, whole milk", "en:plain-yogurt"),
    ("yogur-griego", "Yogur griego natural", "Yogurt, Greek, plain, nonfat (Includes foods for USDA's Food Distribution Program)", "en:greek-yogurt"),
    ("queso-cottage", "Queso cottage", "Cheese, cottage, lowfat, 2% milkfat", "en:cottage-cheese"),
    ("queso-curado", "Queso curado", "Cheese, parmesan, hard", "en:hard-cheese"),
    ("mozzarella", "Mozzarella", "Cheese, mozzarella, part skim milk", "en:mozzarella"),
    ("requeson", "Requesón", "Cheese, ricotta, part skim milk", "en:ricotta"),
    ("mantequilla", "Mantequilla", "Butter, salted", "en:butter"),
    ("nata", "Nata para cocinar", "Cream, fluid, light whipping", "en:cream"),
    # Vegetales proteicos
    ("tofu", "Tofu", "Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)", "en:tofu"),
    ("tempeh", "Tempeh", "Tempeh", "en:soya"),
    ("bebida-soja", "Bebida de soja", "Soymilk, original and vanilla, unfortified", "en:soya"),
    ("bebida-arroz", "Bebida de arroz", "Beverages, rice milk, unsweetened", "en:rice"),
    ("hummus", "Hummus", "Hummus, commercial", "en:chickpea"),
    # Grasas y frutos secos
    ("aceite-oliva", "Aceite de oliva virgen extra", "Oil, olive, salad or cooking", "en:olive-oil"),
    ("aceite-girasol", "Aceite de girasol", "Oil, sunflower, high oleic (70% and over)", "en:sunflower-oil"),
    ("aceitunas", "Aceitunas", "Olives, ripe, canned (small-extra large)", "en:olive"),
    ("almendras", "Almendras", "Nuts, almonds", "en:almond"),
    ("nueces", "Nueces", "Nuts, walnuts, english", "en:walnut"),
    ("cacahuetes", "Cacahuetes", "Peanuts, all types, raw", "en:peanut"),
    ("pipas-girasol", "Pipas de girasol", "Seeds, sunflower seed kernels, dried", "en:sunflower-seed"),
    ("chia", "Semillas de chía", "Seeds, chia seeds, dried", "en:chia-seed"),
    ("tahini", "Tahini", "Seeds, sesame butter, tahini, from roasted and toasted kernels (most common type)", "en:tahini"),
    # Otros
    ("azucar", "Azúcar", "Sugars, granulated", "en:sugar"),
    ("miel", "Miel", "Honey", "en:honey"),
    ("sal", "Sal", "Salt, table", "en:salt"),
    ("pimenton", "Pimentón", "Spices, paprika", "en:paprika"),
    ("comino", "Comino", "Spices, cumin seed", "en:cumin"),
    ("oregano", "Orégano", "Spices, oregano, dried", "en:oregano"),
    ("laurel", "Laurel", "Spices, bay leaf", "en:bay-leaf"),
    ("pimienta", "Pimienta negra", "Spices, pepper, black", "en:black-pepper"),
    ("vinagre", "Vinagre", "Vinegar, distilled", "en:vinegar"),
    ("chocolate-negro", "Chocolate negro", "Baking chocolate, unsweetened, squares", "en:dark-chocolate"),
    ("cacao", "Cacao en polvo", "Cocoa, dry powder, unsweetened", "en:cocoa-powder"),
    ("caldo-verduras", "Caldo de verduras", "Soup, vegetable broth, ready to serve", "en:vegetable-broth"),
]


# ---------------------------------------------------------------------------
# Los mismos ingredientes en inglés, para la versión inglesa de la aplicación.
# Se escriben como los llamaría alguien en una cocina, no como los nombra la
# base de datos de la USDA («Lentils, mature seeds, cooked, boiled»).
EN = {
    "lentejas": "Cooked lentils",
    "garbanzos": "Cooked chickpeas",
    "alubias-blancas": "Cooked white beans",
    "judias-pintas": "Cooked pinto beans",
    "guisantes": "Peas",
    "proteina-soja": "Soya protein",
    "arroz-blanco": "Cooked white rice",
    "arroz-integral": "Cooked brown rice",
    "pasta": "Cooked pasta",
    "pasta-integral": "Cooked wholewheat pasta",
    "pan": "White bread",
    "pan-integral": "Wholemeal bread",
    "avena": "Rolled oats",
    "quinoa": "Cooked quinoa",
    "cuscus": "Cooked couscous",
    "harina-trigo": "Wheat flour",
    "maiz-dulce": "Sweetcorn",
    "cebolla": "Onion",
    "ajo": "Garlic",
    "tomate": "Tomato",
    "tomate-triturado": "Crushed tomatoes",
    "pimiento": "Pepper",
    "calabacin": "Courgette",
    "berenjena": "Aubergine",
    "zanahoria": "Carrot",
    "patata": "Potato",
    "boniato": "Sweet potato",
    "brocoli": "Broccoli",
    "coliflor": "Cauliflower",
    "espinacas": "Spinach",
    "acelgas": "Chard",
    "judias-verdes": "Green beans",
    "champinones": "Mushrooms",
    "puerro": "Leek",
    "calabaza": "Pumpkin",
    "lechuga": "Lettuce",
    "pepino": "Cucumber",
    "col": "Cabbage",
    "apio": "Celery",
    "manzana": "Apple",
    "platano": "Banana",
    "naranja": "Orange",
    "limon": "Lemon",
    "fresas": "Strawberries",
    "aguacate": "Avocado",
    "pera": "Pear",
    "uvas": "Grapes",
    "datiles": "Dates",
    "pasas": "Raisins",
    "pollo": "Chicken breast",
    "pavo": "Turkey breast",
    "ternera": "Lean beef",
    "cerdo-lomo": "Pork loin",
    "jamon": "Sliced ham",
    "huevo": "Egg",
    "atun-lata": "Tinned tuna in brine",
    "salmon": "Salmon",
    "bacalao": "Cod",
    "sardinas": "Tinned sardines",
    "gambas": "Prawns",
    "mejillones": "Mussels",
    "leche-entera": "Whole milk",
    "leche-desnatada": "Skimmed milk",
    "yogur-natural": "Natural yoghurt",
    "yogur-griego": "Greek yoghurt",
    "queso-cottage": "Cottage cheese",
    "queso-curado": "Mature cheese",
    "mozzarella": "Mozzarella",
    "requeson": "Ricotta",
    "mantequilla": "Butter",
    "nata": "Single cream",
    "tofu": "Tofu",
    "tempeh": "Tempeh",
    "bebida-soja": "Soya drink",
    "bebida-arroz": "Rice drink",
    "hummus": "Hummus",
    "aceite-oliva": "Extra virgin olive oil",
    "aceite-girasol": "Sunflower oil",
    "aceitunas": "Olives",
    "almendras": "Almonds",
    "nueces": "Walnuts",
    "cacahuetes": "Peanuts",
    "pipas-girasol": "Sunflower seeds",
    "chia": "Chia seeds",
    "tahini": "Tahini",
    "azucar": "Sugar",
    "miel": "Honey",
    "sal": "Salt",
    "pimenton": "Paprika",
    "comino": "Cumin",
    "oregano": "Oregano",
    "laurel": "Bay leaf",
    "pimienta": "Black pepper",
    "vinagre": "Vinegar",
    "chocolate-negro": "Dark chocolate",
    "cacao": "Cocoa powder",
    "caldo-verduras": "Vegetable stock",
}
